name: Production

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

# This workflow does not support fixing old versions
# as this will break the latest and major tags

jobs:
  docker-build:
    name: Build Docker
    runs-on: ${{ matrix.arch.os }}
    if: |
      github.repository_owner == 'cgm616' &&
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: linux/arm64
            os: ubuntu-24.04-arm
          - platform: linux/arm/v7
            os: ubuntu-24.04-arm
          - platform: linux/arm/v6
            os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          platform=${{ matrix.arch.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/cgm616/wg-easy
          flavor: |
            latest=true
          tags: |
            type=match,pattern=v((\d+)\.(\d+)\.(\d+)(.*))#cgm616,group=1
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=1
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=2
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.arch.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/cgm616/wg-easy
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=min,scope=build-${{ env.PLATFORM_PAIR }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  docker-merge:
    name: Merge & Deploy Docker
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'cgm616' &&
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write
    needs: docker-build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/cgm616/wg-easy
          flavor: |
            latest=true
          tags: |
            type=match,pattern=v((\d+)\.(\d+)\.(\d+)(.*))#cgm616,group=1
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=1
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=2
            type=match,pattern=v(((\d+)\.(\d+))\.(\d+))#cgm616,group=3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/cgm616/wg-easy@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/cgm616/wg-easy:${{ steps.meta.outputs.version }}
